@startuml packages_pokemon_project
set namespaceSeparator none
package "main" as main {
}
package "models" as models {
}
package "models.pokemon" as models.pokemon {
}
package "models.pokemon_builder" as models.pokemon_builder {
}
package "services" as services {
}
package "services.csv_analyzer" as services.csv_analyzer {
}
package "services.csv_writer" as services.csv_writer {
}
package "services.logging" as services.logging {
}
package "services.pokemon_crawler" as services.pokemon_crawler {
}
package "services.quests" as services.quests {
}
main --> services.csv_analyzer
main --> services.csv_writer
main --> services.logging
main --> services.pokemon_crawler
main --> services.quests
models.pokemon_builder --> models.pokemon
services.pokemon_crawler --> models.pokemon
services.pokemon_crawler --> models.pokemon_builder
@enduml
